[project]
name = "to-do-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "pymongo>=4.15.3",
    "python-dotenv>=1.2.1",
]
